# To use:
#
#     pre-commit run -a
#
# Or:
#
#     pre-commit install  # (runs every time you commit in git)
#
# To update this file:
#
#     pre-commit autoupdate
#
# See https://github.com/pre-commit/pre-commit

repos:
# Standard hooks
- repo: https://github.com/pre-commit/pre-commit-hooks
  # From rev v4.1.0 upwards needs git >= 1.8.5.
  rev: v4.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-json
  - id: check-yaml
  - id: check-toml
  - id: check-xml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
  - id: file-contents-sorter
  - id: trailing-whitespace
    exclude: ^doc/_static/.*.svg

# Python linter (Flake8)
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
    args:
    - "--max-line-length=88"
    # E203: whitespace before ':'
    - "--extend-ignore=E203"

# Python formatting
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

# Python black(en) for docs
- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==22.1.0]

# pyupgrade
- repo: https://github.com/asottile/pyupgrade
  rev: v2.31.1
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]

# Sorted python imports
- repo: https://github.com/PyCQA/isort
  rev: 5.10.1
  hooks:
    - id: isort
      args: ["--profile", "black"]

# Jupyter notebook quality control
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.3.1
  hooks:
  - id: nbqa-flake8
  - id: nbqa-black
  - id: nbqa-pyupgrade
# While I found out how to keep isort from overwriting the black changes,
# I can't manage to get this done for the nbqa versions.
# Thus, let's fo without nbqa-isort for now.
#  - id: nbqa-isort
#    args: [--nbqa-mutate]

# Exclude kept as a reminder for that being possible
- repo: https://github.com/kynan/nbstripout
  rev: 0.5.0
  hooks:
    - id: nbstripout
      exclude: ^tests/data/databricks_notebook\.ipynb$
