# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: eehiq analysis
author: Jonas Kunath, LLR
copyright: "2022"
logo: assets/logo_llrild.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  timeout: 300

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/LLR-ILD/eehiq
  path_to_book: docs
  branch: master

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  baseurl: https://llr.in2p3.fr/~kunath/eehiq/
  use_edit_page_button: true
  use_repository_button: true
  comments:
    hypothesis: true

launch_buttons:
  notebook_interface        : jupyterlab
  binderhub_url             : ""
  # binderhub_url             : https://mybinder.org
  # jupyterhub_url            : https://polui01.in2p3.fr
